/**
 * Node of a binary search tree storing {@link Physical} key-value pairs.
 *
 * <p>The subtree is ordered according to a {@link PhysicalComparator}.
 * Search and insertion decisions use this order relation.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE.
 */
public class PhysicalPhysicalTreeMapNodeNonEmpty implements PhysicalPhysicalTreeMapNode {

    private Physical key;
    private Physical value;

    private PhysicalPhysicalTreeMapNode left;
    private PhysicalPhysicalTreeMapNode right;

    /**
     * Creates a new node with the specified key-value pair.
     *
     * @param key the key stored in this node; {@code key != null}
     * @param value the associated value; {@code value != null}
     */
    public PhysicalPhysicalTreeMapNodeNonEmpty(Physical key, Physical value) {

        this.key = key;
        this.value = value;
        left = right = PhysicalPhysicalTreeMapNodeEmpty.EMPTY;
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public PhysicalPhysicalTreeMapNode getLeft() {
        return left;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhysicalPhysicalTreeMapNode getRight() {
        return right;
    }

    /**
     * Inserts a key-value pair into this subtree or updates an existing entry unsing the specified comparator.
     *
     * <p>If a key object equal to the specified key is already stored in this subtree,
     * its associated value is replaced by
     * {@code value}, and the previous value is returned.</p>
     *
     * <p>Otherwise, a new node is inserted according to the comparator-defined
     * search tree order.</p>
     *
     * @param key the key to insert; {@code key != null}
     * @param value the associated value; {@code value != null}
     * @return the previously associated value if the same key object already existed,
     *         otherwise {@code null}
     */
    @Override
    public PhysicalPhysicalTreeMapNode put(Physical key, Physical value, PhysicalComparator comparator, Physical[] oldValueBox) {

        if (this.key.equals(key)) {
            oldValueBox[0] = this.value;
            this.value = value;
            return this;
        }

        int cmp = comparator.compare(key, this.key);

        if (cmp < 0) {
            left = left.put(key, value, comparator, oldValueBox);
        } else {
            right = right.put(key, value, comparator, oldValueBox);
        }
        return this;
    }

    /**
     * Returns the value associated with the given key object.
     *
     * @param key the key to search for; {@code key != null}
     * @return the associated value if the same key object is found,
     *         otherwise {@code null}
     */
    @Override
    public Physical get(Physical key, PhysicalComparator comparator) {

        if (this.key.equals(key)) {
            return value;
        }

        int cmp = comparator.compare(key, this.key);

        if (cmp < 0) {
            return left.get(key, comparator);
        } else {
            return right.get(key, comparator);
        }
    }

    /**
     * Returns whether this subtree contains a key equal to the specified key object.
     *
     * @param key the key to search for; {@code key != null}
     * @return {@code true} iff the same key object occurs in this subtree
     */
    @Override
    public boolean containsKey(Physical key, PhysicalComparator comparator) {

        if (this.key.equals(key)) {
            return true;
        }

        int cmp = comparator.compare(key, this.key);

        if (cmp < 0) {
            return left.containsKey(key, comparator);
        } else {
            return right.containsKey(key, comparator);
        }
    }

    /**
     * Returns whether the given physical object is equal to a value in this subtree.
     *
     * @param value the value to search for; {@code value != null}
     * @return {@code true} iff the same value object occurs in this subtree
     */
    @Override
    public boolean containsValue(Physical value) {

        if (this.value.equals(value)) {
            return true;
        }

        return left.containsValue(value) || right.containsValue(value);
    }

    /**
     * Adds all keys to the given set.
     *
     * @param result the set to which keys are added; {@code result != null}
     */
    @Override
    public void fillKeys(PhysicalSet result) {

        left.fillKeys(result);
        result.add(key);
        right.fillKeys(result);
    }

    /**
     * Adds all values to the given set.
     *
     * @param result the set to which values are added; {@code result != null}
     */
    @Override
    public void fillValues(PhysicalSet result) {

        result.add(value);
        left.fillValues(result);
        right.fillValues(result);
    }

    /**
     * Returns a string representation of this subtree using the specified indentation.
     *
     * @param indent the indentation prefix for this node
     * @return a string representation of this subtree
     */
    @Override
    public String toIndentedString(String indent) {

        String result = indent + key.toString() + " -> " + value.toString() + "\n";

        result += left.toIndentedString(indent + "  ");
        result += right.toIndentedString(indent + "  ");

        return result;
    }
}