/**
 * Node of a binary search tree storing {@link Physical} objects.
 *
 * <p>The subtree rooted at such a node is ordered according to a
 * {@link PhysicalComparator}. Search and insertion decisions use this
 * order relation to decide whether traversal continues in the left or
 * right subtree.</p>
 *
 * <p>Duplicate elements are not stored. Two elements are considered
 * duplicates iff they are equal according to
 * {@link Physical#equals(Object)}.</p>
 *
 * <p>This interface represents the root node of a subtree.
 * An implementation may represent either an empty subtree or a
 * non-empty subtree.</p>
 *
 * PLEASE DO NOT EDIT THIS FILE.
 */
public interface PhysicalTreeSetNode extends PhysicalIterableTreeNode {

    /**
     * Returns the {@link Physical} object stored at the root of this subtree.
     *
     * @return the stored object, or {@code null} if this subtree is empty
     */
    Physical getValue();

    /**
     * Returns the left child subtree of this node.
     *
     * <p>The left subtree contains only elements that compare smaller than
     * the elements stored in this node according to the comparator used by the
     * surrounding tree set.</p>
     *
     * The returned subtree may be an empty node.
     *
     * @return the left child node (never {@code null}).
     */
    PhysicalTreeSetNode getLeft();

    /**
     * Returns the right child subtree of this node.
     *
     * <p>The right subtree contains only elements that compare greater than
     * the elements stored in this node according to the comparator used by the
     * surrounding tree set.</p>
     *
     * The returned subtree may be an empty node.
     *
     * @return the right child node (never {@code null}).
     */
    PhysicalTreeSetNode getRight();

    /**
     * Returns whether this subtree contains an element equal to the
     * specified object.
     *
     * @param p the object to search for; {@code p != null}
     * @param comparator the comparator defining the tree order;
     *                   {@code comparator != null}
     * @return {@code true} if an equal object exists in this subtree,
     *         otherwise {@code false}
     */
    boolean contains(Physical p, PhysicalComparator comparator);

    /**
     * Inserts the specified object into this subtree and returns the
     * root of the resulting subtree.
     *
     * <p>If an equal object already exists in this subtree,
     * the subtree remains unchanged.</p>
     *
     * <p>Otherwise, a new node is inserted according to the ordering
     * defined by {@code comparator}.</p>
     *
     * @param p the object to insert; {@code p != null}
     * @param comparator the comparator defining the tree order;
     *                   {@code comparator != null}
     * @return the root of the resulting subtree after insertion
     */
    PhysicalTreeSetNode insert(Physical p, PhysicalComparator comparator);

    /**
     * Returns the number of elements stored in this subtree.
     *
     * @return the number of stored elements
     */
    int size();
}